### ISSUE TITLE
Error: must define the 'cookie_secret' setting in your application to use secure cookies

### ISSUE THREAD

**Issue by rth** [icubam/icubam#107]
For future reference, getting when following `dev_install.md` and trying to open the web-page. Possibly because I run it on a remote server not localhost. Will investigate,
```
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/rth/src/icubam/icubam/www/handlers/update.py", line 35, in get
    self.set_secure_cookie(self.COOKIE, user_token)
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 714, in set_secure_cookie
    self.create_signed_value(name, value, version=version),
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 733, in create_signed_value
    self.require_setting("cookie_secret", "secure cookies")
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 1582, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies
```

**Comment by tgy** [comment]
had this problem too and i had to set `cookie_secret` to some value. i'll slack you
