### ISSUE TITLE
backoffice: /list_icus HTTP 500 internal server error

### ISSUE THREAD

**Issue by rth** [icubam/icubam#149]
Getting a HTTP 500 internal server error on `/list_icus` in backoffice with fake DB data,

```
Uncaught exception GET /list_icus (192.168.1.24)
HTTPServerRequest(protocol='http', host='192.168.1.19:8890', method='GET', uri='/list_icus', version='HTTP/1.1', remote_ip='192.168.1.24')
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 3174, in wrapper
    return method(self, *args, **kwargs)
  File "/home/rth/src/icubam/icubam/backoffice/handlers/icus.py", line 26, in get
    data = [self.prepare_for_table(icu) for icu in icus]
  File "/home/rth/src/icubam/icubam/backoffice/handlers/icus.py", line 26, in <listcomp>
    data = [self.prepare_for_table(icu) for icu in icus]
  File "/home/rth/src/icubam/icubam/backoffice/handlers/icus.py", line 16, in prepare_for_table
    result['region'] = result.pop('region', {}).get('name', '-')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by rth** [comment]
No never mind, probably a DB schema issue. Re-generating the DB with fake data following latest instructions following https://github.com/icubam/icubam/pull/117 fixed it.
