### ISSUE TITLE
scripts/run_server.py --server=all broken in python=3.8.2

### ISSUE THREAD

**Issue by dulacarnold** [icubam/icubam#272]
This used to work with 3.7, it's not used in prod but would be good to make sure this either works or is deprecated (preference for working).

**Comment by rth** [comment]
Can you provide a traceback?

**Comment by rth** [comment]
At least for me the error is,
```
Traceback (most recent call last):
I0415 18:03:27.733662 139923899303744 server.py:117] Access the backoffice at http://localhost:8890/bo/
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rth/src/icubam/icubam/base_server.py", line 49, in run
    app.listen(self.port)
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 2112, in listen
    server.listen(port, address)
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Process Process-2:
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: users.consent
```

**Comment by maximedenes** [comment]
> OSError: [Errno 98] Address already in use

This looks like the same port was already used on the same host. Could it be that you have another instance of the server running?

> sqlite3.OperationalError: no such column: users.consent

This looks like your DB is too old (before consent was stored). Could it be the case?

Did you confirm this still works with Python 3.7?

**Comment by rth** [comment]
> This looks like the same port was already used on the same host. Could it be that you have another instance of the server running?

Not sure what happened there, yes it was temporary and not reporoducible.

> This looks like your DB is too old (before consent was stored). Could it be the case?

Well I can start www and backoffice service fine, but the messaging service does yield the above error.


The questions is what error @dulacarnold saw..

**Comment by dulacarnold** [comment]
I get 
```I0415 22:37:17.461254 4574590400 base_server.py:35] BackOfficeServer: HealthHandler serving on /admin/health
Traceback (most recent call last):
  File "/Users/dulacarnold/Src/icubam/scripts/run_server.py", line 43, in <module>
    app.run(main)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/dulacarnold/Src/icubam/scripts/run_server.py", line 39, in main
    p.start()
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/dulacarnold/miniconda2/envs/icubam/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'NoneType' object is not callable```

I tried digging into it but couldn't quite figure out why, as the process_obj didn't seem to be None...
