### ISSUE TITLE
Typos in department names

### ISSUE THREAD

**Issue by rth** [icubam/icubam#312]
On the topic of typos in the department names. Here is what can happen when generating plots on production data,
```
Traceback (most recent call last):
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/rth/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/rth/src/icubam/icubam/predicu/analytics_server.py", line 23, in generate_plots
    generate_plots(
  File "/home/rth/src/icubam/icubam/predicu/plot/__init__.py", line 159, in generate_plots
    plot(
  File "/home/rth/src/icubam/icubam/predicu/plot/__init__.py", line 121, in plot
    fig, tikzplotlib_kwargs = plot_fun(data=cached_data[data_source].copy())
  File "/home/rth/src/icubam/icubam/predicu/plot/barplot_deaths_per_dept_and_day.py", line 43, in plot
    facecolor=DEPARTMENT_COLOR[department],
KeyError: "Cotes-d'armor"
```
The key should have been `Côtes-d'Armor` there.

 - [ ] In the short term we should have a way to correct such typos as suggested by @tgy 
 - [ ] In the long term, as suggested by @olivierteboul  maybe everything should be purely in the DB and entered by users. https://github.com/icubam/icubam/pull/308 would help avoiding typos in that case. But then it's less clear how to provide this information to users who use only `icubam.predicu` with a CSV dump.

**Comment by rth** [comment]
I think this is less of an issue with the new processing worflow, and since we added drop-down lists for departments.
